### ISSUE TITLE
Errors should include request data (e.g. requested URL)

### ISSUE THREAD

**Issue by jhob** [goodeggs/json-fetch#15]
We're seeing logged errors (`Unexpected fetch response status 500/401`) but there's no data included with the errors describing the request parameters. In particular we're missing the URL being fetched. It seems like useful data to include on all `json-fetch` errors by default?

**Comment by makebbekus** [comment]
Yes please!

**Comment by serhalp** [comment]
Closed by https://github.com/goodeggs/json-fetch/pull/16
